### DISCUSSION TITLE
hide option

### DISCUSSION THREAD

**Discussion by sp2003** [iantrich/restriction-card#107] [Q&A]
```
type: entities
entities:
  - entity: switch.8ch_5_relay_pdc
    name: PdC
    icon: mdi:heat-pump-outline
  - type: custom:restriction-card
    restrictions:
      confirm:
        text: sure?
    card:
      entity: switch.8ch_6_enable_disable_pdc
      name: Disable PdC
      icon: mdi:power
    row: true
```
I haven't found anything that can help me on the home of the repo:
I would like that when switch.8ch_6_enable_disable_pdc becomes ON, its name changes to "Enable PdC" and that switch.8ch_5_pdc_relay gets stuck on OFF or disappears from the card and remains so until switch.8ch_6_enable_disable_pdc returns to OFF. Is it possible?
