### DISCUSSION TITLE
Help with condtion based on counter

### DISCUSSION THREAD

**Discussion by Geddard** [iantrich/restriction-card#111] [Q&A]
Hey there I've been trying to lock a button depending on a sensor that returns a number.

```
- type: custom:restriction-card
        restrictions:
          block:
            text: No rooms selected
            condition:
              entity: sensor.selected_rooms_count
        card:
          type: button
          show_icon: true
          show_name: true
          entity: input_button.go_clean
          name: Start cleaning
          icon_height: 25px
          tap_action:
            action: toggle
```

I can't figure out how to make the condition block the button when the count is falsy

Thanks for the help!

**Comment by Geddard** [comment]
Ok chat GPT helped me get this to make it work:

```
      - type: custom:restriction-card
        restrictions:
          block:
            text: No rooms selected
            condition:
              value: '0'
              entity: sensor.selected_rooms_count
              operator: '=='
```

But i dont like that i have to double click the button now when the condition is passing, any way to just automatically unlock it when the count is over 0?

**Comment by ildar170975** [comment]
You are confusing "lock" with "block".
Block = disable unlocking.

**Reply by Geddard** [reply]
uhm im not sure i understand, do you mean that i can change the behavior to lock instead of block and get what i want?
I couldn't find a more fitting add-on for my scenario, and i like that this pops up a native notification when the thing is blocked.


I'm not sure if you are saying i shouldn't use your addon for what i'm asking?

Thanks for the help :)

**Reply by ildar170975** [reply]
Check this:
```
type: vertical-stack
cards:

  - type: custom:restriction-card
    condition:
      entity: input_boolean.test_boolean_3
      operator: '=='
      value: 'on'
    action: hold
    duration: 2
    card:
      type: entities
      entities:
        - entity: input_boolean.test_boolean

  - type: entities
    entities:
      - entity: input_boolean.test_boolean_3
        name: lock
```
![image](https://github.com/iantrich/restriction-card/assets/71872483/312894b9-5b85-4731-8d05-9d759f70de3e)

![image](https://github.com/iantrich/restriction-card/assets/71872483/619ff04b-db34-4bc1-94ea-bc11766cb124)
