### DISCUSSION TITLE
Restricted Card for Turn Off Only

### DISCUSSION THREAD

**Discussion by jwidess** [iantrich/restriction-card#166] [Q&A]
Hi all,
I looked through this discussions section for anyone trying to do this and couldn't find quite what I was looking for. I have my 3D Printer hooked up to a smart switch and I want to make it harder to accidentally turn the device off, but easy to turn the device on. I am using the YAML below on a dashboard which works, but the condition isn't applying to bypass the restriction when the device is off. Currently, when I click the card once, the lock fades away and if I click again I get the popup to toggle the state. However I would like this to only happen when turning off the device. When the device is off, I would like the first click to turn it on. Thanks for the help, I really appreciate it!

```YAML
type: custom:restriction-card
card:
  type: entity
  entity: switch.topgreener_apm_4_relay
  name: 3D Printer Power
  icon: mdi:printer-3d
  tap_action:
    action: toggle
conditions:
  - entity: switch.topgreener_apm_4_relay
    value: "off"
``` 

P.S. I found [this discussion](https://github.com/iantrich/restriction-card/discussions/77) which is similar to what I want to do, but couldn't quite figure out how to utilize their setup.

**Comment by ildar170975** [comment]
> and if I click again I get the popup to toggle the stat

Note that the Entity card does not support actions, i.e. this code does not work and can be removed:
```
  tap_action:
    action: toggle
```

And here there are errors:
```
conditions:
  - entity: switch.topgreener_apm_4_relay
    value: "off"
```

Check this code:
```
type: custom:restriction-card
card:
  type: entity
  entity: switch.topgreener_apm_4_relay
  name: 3D Printer Power
  icon: mdi:printer-3d
condition:
  entity: switch.topgreener_apm_4_relay
  operator: "=="
  value: "off"
```
