### ISSUE TITLE
restriction-card read-only toggle bug

### ISSUE THREAD

**Issue by karol-dubas** [iantrich/restriction-card#106]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
RESTRICTION-CARD
Version 1.2.9   

**Browser and Operating System:**
BraveVersion 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)

Edition	Windows 10 Pro
Version	22H2
Installed on	‎04/‎05/‎2023
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Description of problem:**

You can change the status of a read-only field by clicking on the location of the red markers
![image](https://github.com/iantrich/restriction-card/assets/70332407/892068ea-284b-4f59-a6bf-cf706f8e544c)

```yaml
card:
  entity: switch.plug_heater
  name: Heater state
  secondary_info: last-changed
restrictions:
  block: true
type: custom:restriction-card
row: true
```
