### ISSUE TITLE
Not working in Home Assistant 2024.3.3

### ISSUE THREAD

**Issue by wgstarks** [iantrich/restriction-card#110]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

1.2.9

**Last working release (if known):**

**Browser and Operating System:**

MacOS Safari, Firefox, Chrome, HA app

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

I'm not seeing anything in the logs.

Sample YAML configuration-
`
type: custom:restriction-card
row: true
card:
  entity: switch.greenhouse_lights_switch
restrictions:
  confirm:
    text: Are you sure you want to turn the lights on/off?
`

**Comment by ildar170975** [comment]
Fix the posted code, it is unformatted. And do not post it as a picture.

**Comment by wgstarks** [comment]
Ok  got it.
```
`type: custom:restriction-card
row: true
card:
  entity: switch.greenhouse_lights_switch
restrictions:
  confirm:
    text: Are you sure you want to turn the lights on/off?
`
```

**Comment by ildar170975** [comment]
The "row" card is supposed to be used in Entities card.
Is it what you do?

**Comment by wgstarks** [comment]
Yes. Here is the entire card-
```
type: entities
entities:
  - entity: sensor.greenhouse_temperature_humidity_greenhouse_temperature
  - entity: sensor.greenhouse_temperature_humidity_greenhouse_humidity
  - type: custom:restriction-card
    row: true
    card:
      entity: switch.greenhouse_lights_switch
    restrictions:
      confirm:
        text: Are you sure you want to turn the lights on/off?
  - type: custom:restriction-card
    row: true
    card:
      entity: switch.greenhouse_heater_greenhouse_heater
    restrictions:
      confirm:
        text: Are you sure you want to turn the heater on/off?
  - entity: binary_sensor.front_door_1_front_door_1
  - entity: binary_sensor.front_door_2_front_door_2
  - entity: switch.greenhouse_lights_switch
    name: Greenhouse Lights
    secondary_info: entity-id
    icon: mdi:lightbulb
  - entity: switch.greenhouse_heater_greenhouse_heater
    secondary_info: entity-id
```
