### ISSUE TITLE
Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by chemelli74** [iantrich/restriction-card#114]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 1.2.9

**Last working release (if known):**

**Browser and Operating System:** Edge Versione 126.0.2592.56  (64bit) on Windows 11 22H2

**Description of problem:**

Hi,

I just took the time to check and fond that this card use _`polimer`_, so I guess is a good candidate for this error log:

```
2024-06-23 14:15:28.842 ERROR (MainThread) [frontend.js.latest.202406101] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'click')
click (node_modules/@polymer/iron-menu-behavior/iron-menubar-behavior.js:35:21)
call (node_modules/@polymer/iron-a11y-keys-behavior/iron-a11y-keys-behavior.js:479:22)
_triggerKeyHandler (node_modules/@polymer/iron-a11y-keys-behavior/iron-a11y-keys-behavior.js:465:13)
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment]
Please post a minimal code causing the issue.

**Comment by chemelli74** [comment]
Hi,

here my car dcode:

```
type: entities
entities:
  - entity: sensor.custom_lavatrice_status
    name: Stato
  - entity: sensor.lavatrice_power
    name: Consumo attuale
  - card:
      entity: switch.lavatrice
      name: Presa
    restrictions:
      pin:
        code: 1111
    condition:
      entity: switch.lavatrice
      value: 'on'
    type: custom:restriction-card
    row: true
  - entity: input_boolean.panni_da_stendere
show_header_toggle: false
title: Lavatrice

```

**Comment by ildar170975** [comment]
Tested with
```
type: entities
entities:
  - entity: sun.sun
    name: Stato
  - entity: sun.sun
    name: Consumo attuale
  - card:
      entity: switch.test_switch
      name: Presa
    restrictions:
      pin:
        code: 1111
    condition:
      entity: switch.test_switch_2
      value: 'on'
    type: custom:restriction-card
    row: true
  - entity: input_boolean.test_boolean
show_header_toggle: false
title: Lavatrice
```
2024.6.2
Observed no errors in Code inspector in Win10x64: Chrome 126.0.6478.62, FF 127, MS Edge.
Also no messages in Log.
