### ISSUE TITLE
Restriction Card does not fill row

### ISSUE THREAD

**Issue by gthbusrr** [iantrich/restriction-card#117]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.2.9
**Last working release (if known):**
New Install
**Browser and Operating System:**
Firefox / MacOS
Firefox / Android
Companion App / Android

**Description of problem:**
![w/ Restriction Card](https://github.com/user-attachments/assets/6a9d41e4-8e35-4e3d-ad77-06abcfb8aec7)
^ w/ Restriction Card
![w/o Restriction Card](https://github.com/user-attachments/assets/3058c0af-c782-46f1-9391-d08c6e8a7f17)

^ w/o Restriction Card

Config:
```
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.motion_detected_lights
      vertical: true
      hide_state: true
      show_entity_picture: false
      name: Motion Sensor - Living Room
      tap_action:
        action: toggle
      icon_tap_action:
        action: toggle
      color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
    card_mod:
      style: |
        ha-card {
          height: 100%
        }
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment]
Retest w/o card-mod which is a separate plugin and not discussed here.

**Comment by ildar170975** [comment]
@gthbusrr 
I see. I am far from a PC, will test it in 10 days.

**Comment by ildar170975** [comment]
@gthbusrr 
Please provide a detailed description of the issue.
What row are you talking about?
Is it a section, grid, .. ?

**Comment by gthbusrr** [comment]
@ildar170975 

Hi it's a section:

Yaml of the section
```yaml
type: grid
cards:
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.leave_home
      vertical: true
      hide_state: true
      show_entity_picture: false
      tap_action:
        action: toggle
      icon_tap_action:
        action: toggle
      color: primary
      name: Leave Home
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.arrived_home
      vertical: true
      hide_state: true
      show_entity_picture: false
      name: Arrive Home
      tap_action:
        action: toggle
      icon_tap_action:
        action: toggle
      color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.door_opened
      vertical: true
      hide_state: true
      show_entity_picture: false
      name: Door Opened
      tap_action:
        action: toggle
      icon_tap_action:
        action: toggle
      color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.front_door_lock_notification
      vertical: true
      hide_state: true
      show_entity_picture: false
      name: Door Lock Notification
      tap_action:
        action: toggle
      icon_tap_action:
        action: toggle
      color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.camera_motion_detected
      vertical: true
      hide_state: true
      show_entity_picture: false
      name: Camera Motion Detection
      tap_action:
        action: toggle
      icon_tap_action:
        action: toggle
      color: primary
    layout_options:
      grid_columns: full
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: custom:card-templater
      card:
        type: tile
        entity: input_boolean.enable_home_security
        hide_state: true
        vertical: true
        show_entity_picture: false
        tap_action:
          action: call-service
          service: input_boolean.toggle
          target:
            entity_id: input_boolean.enable_home_security
        icon_tap_action:
          action: call-service
          service: input_boolean.toggle
          target:
            entity_id: input_boolean.enable_home_security
        name_template: >-
          Home Security {% if is_state('input_boolean.enable_home_security',
          'on') %} Enabled {% else %} Disabled {% endif %}
        card_mod:
          style: |
            ha-tile-icon {
              {% if is_state('input_boolean.enable_home_security', 'on') %}
              --tile-color: orange !important;
              {% else %}
              --tile-color: grey !important;
              {% endif %}
            }
      entities:
        - input_boolean.enable_home_security
    layout_options:
      grid_columns: full
      grid_rows: 2
title: Home Security
```

This is what it looks like now (w/ the yaml above)
![image](https://github.com/user-attachments/assets/1be62836-68bb-43b1-9983-fbb89ca70aa5)

Expected result:
![image](https://github.com/user-attachments/assets/8217186a-ed03-4ec1-869e-45c02cca7f59)
Achieved by:
```yaml
type: grid
cards:
  - type: tile
    entity: automation.leave_home
    vertical: true
    hide_state: true
    show_entity_picture: false
    tap_action:
      action: toggle
    icon_tap_action:
      action: toggle
    color: primary
    name: Leave Home
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.arrived_home
    vertical: true
    hide_state: true
    show_entity_picture: false
    name: Arrive Home
    tap_action:
      action: toggle
    icon_tap_action:
      action: toggle
    color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.door_opened
    vertical: true
    hide_state: true
    show_entity_picture: false
    name: Door Opened
    tap_action:
      action: toggle
    icon_tap_action:
      action: toggle
    color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.front_door_lock_notification
    vertical: true
    hide_state: true
    show_entity_picture: false
    name: Door Lock Notification
    tap_action:
      action: toggle
    icon_tap_action:
      action: toggle
    color: primary
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.camera_motion_detected
    vertical: true
    hide_state: true
    show_entity_picture: false
    name: Camera Motion Detection
    tap_action:
      action: toggle
    icon_tap_action:
      action: toggle
    color: primary
    layout_options:
      grid_columns: full
      grid_rows: 2
  - type: custom:card-templater
    card:
      type: tile
      entity: input_boolean.enable_home_security
      hide_state: true
      vertical: true
      show_entity_picture: false
      tap_action:
        action: call-service
        service: input_boolean.toggle
        target:
          entity_id: input_boolean.enable_home_security
      icon_tap_action:
        action: call-service
        service: input_boolean.toggle
        target:
          entity_id: input_boolean.enable_home_security
      name_template: >-
        Home Security {% if is_state('input_boolean.enable_home_security', 'on')
        %} Enabled {% else %} Disabled {% endif %}
      card_mod:
        style: |
          ha-tile-icon {
            {% if is_state('input_boolean.enable_home_security', 'on') %}
            --tile-color: orange !important;
            {% else %}
            --tile-color: grey !important;
            {% endif %}
          }
    entities:
      - input_boolean.enable_home_security
    layout_options:
      grid_columns: full
      grid_rows: 2
title: Home Security
```

**Comment by ildar170975** [comment]
You have plenty of custom cards/plugins unrelated to the restriction-card.
Suggest you to prepare a SHORT minimal working example.

**Comment by gthbusrr** [comment]
@ildar170975
Here's an example with only restriction-card & built in tile card:
![image](https://github.com/user-attachments/assets/ebdfb923-3ecc-4a8b-bed8-8333162e4e3f)

```yaml
type: grid
cards:
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.leave_home
      vertical: true
      hide_state: true
      show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.arrived_home
      vertical: true
      hide_state: true
      show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.door_opened
      vertical: true
      hide_state: true
      show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: custom:restriction-card
    card:
      type: tile
      entity: automation.front_door_lock_notification
      vertical: true
      hide_state: true
      show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
title: Home Security

```

Expected result:
![image](https://github.com/user-attachments/assets/28eb59af-b644-42a2-958d-f3c52b22c8de)


```yaml
type: grid
cards:
  - type: tile
    entity: automation.leave_home
    vertical: true
    hide_state: true
    show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.arrived_home
    vertical: true
    hide_state: true
    show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.door_opened
    vertical: true
    hide_state: true
    show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
  - type: tile
    entity: automation.front_door_lock_notification
    vertical: true
    hide_state: true
    show_entity_picture: false
    layout_options:
      grid_columns: 2
      grid_rows: 2
title: Home Security
```

**Comment by gthbusrr** [comment]
@ildar170975 
1. The `layout_options` is part of the `section`. See https://www.home-assistant.io/blog/2024/09/04/release-20249/#sections-go-big
2. "Sections" is the dashboard view type, in the dashboard, there are individual "Sections". When you edit the individual "section", the header shows `Edit section`. See terminology used in Home Assistant Documentation for Sections: https://www.home-assistant.io/dashboards/sections/#deleting-a-section
    a. I tried your yaml but it either makes it extra large: 
![image](https://github.com/user-attachments/assets/cb01ab16-8b6a-49fc-bd64-5dc246170873)
```yaml
type: custom:mod-card
card_mod:
  style:
    hui-grid-card $:
      hui-card:
        restriction-card $: |
          :first-child, div#card {
            height: 100%;
          }
        .: |
          restriction-card {
            height: 100%;
          }
card:
  type: grid
  columns: 2
  cards:
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.leave_home
        vertical: true
        hide_state: true
        show_entity_picture: false
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
        name: Leave Home
      layout_options:
        grid_columns: 2
        grid_rows: 2
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.arrived_home
        vertical: true
        hide_state: true
        show_entity_picture: false
        name: Arrive Home
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
      layout_options:
        grid_columns: 2
        grid_rows: 2
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.door_opened
        vertical: true
        hide_state: true
        show_entity_picture: false
        name: Door Opened
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
      layout_options:
        grid_columns: 2
        grid_rows: 2
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.front_door_lock_notification
        vertical: true
        hide_state: true
        show_entity_picture: false
        name: Door Lock Notification
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
      layout_options:
        grid_columns: 2
        grid_rows: 2
title: Home Security
```
or extra tiny:
![image](https://github.com/user-attachments/assets/2c18b1fc-f0a5-472e-a317-c5724d038e62)
```yaml
type: custom:mod-card
card_mod:
  style:
    hui-grid-card $:
      hui-card:
        restriction-card $: |
          :first-child, div#card {
            height: 100%;
          }
        .: |
          restriction-card {
            height: 100%;
          }
card:
  type: grid
  columns: 2
  square: false
  cards:
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.leave_home
        vertical: true
        hide_state: true
        show_entity_picture: false
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
        name: Leave Home
      layout_options:
        grid_columns: 2
        grid_rows: 2
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.arrived_home
        vertical: true
        hide_state: true
        show_entity_picture: false
        name: Arrive Home
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
      layout_options:
        grid_columns: 2
        grid_rows: 2
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.door_opened
        vertical: true
        hide_state: true
        show_entity_picture: false
        name: Door Opened
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
      layout_options:
        grid_columns: 2
        grid_rows: 2
    - type: custom:restriction-card
      card:
        type: tile
        entity: automation.front_door_lock_notification
        vertical: true
        hide_state: true
        show_entity_picture: false
        name: Door Lock Notification
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        color: primary
      layout_options:
        grid_columns: 2
        grid_rows: 2
title: Home Security
```
