### ISSUE TITLE
Strange Switches behaviour

### ISSUE THREAD

**Issue by gio-dot** [iantrich/restriction-card#118]
As you can see in the video, switches does'nt respond correctly. This make addon use very frustrating because you can't say is the switch is done or not. Here is my code. All HA and addons are updated to latest version. Is there a solution?
```
type: custom:hui-entities-card
entities:
  - card:
      entity: switch.presa_tv_sony
    restrictions:
      pin:
        code: 2244
    type: custom:restriction-card
    row: true
    duration: 10
  - type: divider
  - card:
      entity: switch.1_laptop_nicola_internet_access
    restrictions:
      pin:
        code: 2244
    type: custom:restriction-card
    row: true
    duration: 10
  - card:
      entity: switch.2_tab_s5e_di_giovanni_internet_access
    restrictions:
      pin:
        code: 2244
    type: custom:restriction-card
    row: true
    duration: 10
  - card:
      entity: switch.4_firestickcamerapatronale_internet_access
    restrictions:
      pin:
        code: 2244
    type: custom:restriction-card
    row: true
    duration: 10
  - card:
      entity: switch.3_tv_sony_kdx55_internet_access
    restrictions:
      pin:
        code: 2244
    type: custom:restriction-card
    row: true
    duration: 10
  - type: divider
  - entity: button.sony_kd_55xe8596_reboot
    name: Sony Reboot
  - entity: button.sony_kd_55xe8596_terminate_apps
    name: Sony Terminate apps
state_color: true
```

https://github.com/user-attachments/assets/aaf98de5-e92c-4f3f-a9f5-1316aae9a663
