### ISSUE TITLE
z-index issue in the android app

### ISSUE THREAD

**Issue by treitlis** [iantrich/restriction-card#119]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.2.9
**Last working release (if known):**
1.2.7
**Browser and Operating System:**

Android app 2024.10.3-full with Android version 12

**Description of problem:**

This is a weird one. The card works fine on a desktop with Mozilla Firefox. 
I use it to lock the better thermostat ui card (https://github.com/KartoffelToby/better-thermostat-ui-card ) to avoid accidental changes in the temperature.
However, the card is not locked in the phone app, but it is locked in a desktop browser. The card config is below:

```
type: custom:restriction-card
restrictions: confirm
action: double_tap
duration: 10
card:
  type: custom:better-thermostat-ui-card
  entity: climate.bedroom_bt
  disable_window: true
  disable_heat: false
  disable_eco: true
  disable_off: false
  disable_battery_warning: false
  disable_buttons: false
  disable_summer: true
  eco_temperature: 8
  name: Bedroom
```
I have the lock icon in the corner visible on the card, just that the lock doesn't work in the phone app.

The suggestion that you provide to change the z-index with card-mod, doesn't seem to work either, as it doesn't change the z-index of the "overlay". The only solution was to add a card-mod change to the better thermostat ui card, thus the config would be:
```
type: custom:restriction-card
restrictions: confirm
action: double_tap
duration: 10
card:
  type: custom:better-thermostat-ui-card
  entity: climate.bedroom_bt
  disable_window: true
  disable_heat: false
  disable_eco: true
  disable_off: false
  disable_battery_warning: false
  disable_buttons: false
  disable_summer: true
  eco_temperature: 8
  name: Bedroom
  card_mod:
    style: |
      ha-card {
         z-index: 0;
        }
```
I want to be clear, that this happens only with this card. If I change the **better-thermostat-ui-card** to a **thermostat** card this bug disappears completely.
Maybe a solution would be to set a higher value of z-index. As I see, the only difference between 1.2.7 that works also on the phone and 1.2.9 is the z-index value, that changed from 50 to 1.
In all honesty, I remember that this worked before, earlier this year, because I was super happy when I found the restriction card to lock the thermostat control, as I was always changing the temperature by mistake while scrolling in the app. As neither the restriction card or the better thermostat card was updated in almost a year, it might be that some app changes caused the bug to surface.

**Comment by ildar170975** [comment]
Please re-test with a stock card since custom cards may have own issues.

**Comment by treitlis** [comment]
As I said, the thermostat card, which is a stock card of HA, works just fine, it doesn't have any of this issues. Its locked on both, the phone app or the desktop browser, without needing any card-mod tweaks.

**Comment by ildar170975** [comment]
I got your point, that is why I asked to test with some other more simple stock card. Just to be sure that this is about with only this custom card.

**Comment by ildar170975** [comment]
Also, please elaborate this, unclear:
> The suggestion that you provide to change the z-index with card-mod, doesn't seem to work either, as it doesn't change the z-index of the "overlay".

What solution do you mean?

**Comment by ildar170975** [comment]
As for card-mod - a possible workaround could be same what you suggested - setting a-index for this custom card. I would suggest you to look at this card’s code and find any “z-index” appearances and then find out a purpose of this change. If it serves some critical task - then probably your card-mod breaks it…

**Comment by treitlis** [comment]
I have other stuff locked with restriction-card on the dashboard, and those cards work perfectly. No matter if on the phone or the app. Thus it is with this card only. I mentioned this in the main post. 

> Also, please elaborate this, unclear:
> 
> > The suggestion that you provide to change the z-index with card-mod, doesn't seem to work either, as it doesn't change the z-index of the "overlay".
> 
> What solution do you mean?

This thing in the readme. 
```

Special Consideration for Input Selects: If you find that the restriction card is blocking something you don't want blocked like an input select, try adjusting the z-index using mod-card

card:
  type: custom:mod-card
  card_mod:
    style: |
      ha-card {
        z-index: 7;
        }
  card:
    type: custom:restriction-card
```
While the solution is not for the exact issue that I encounter, the card-mod creates a new ha-card HTML container that has the z-index set to what you ask in the code. However inside this ha-card is the restriction card AND the card that should be restricted, so by inheritance, both will have the same z-index value. 

I also noted in the first post, that 1.2.7 works fine, on both phone and desktop. There you had a z-index of 50.
I investigated carefully, and I noticed that some parts of the better-thermostat-ui-card has z-index of 1 or 3 set for certain components (like the plus and minus buttons, see the screenshot below). This is actually what breaks the whole thing, and now it makes sense. Still, it doesn't make sense why these are blocked on the desktop browser while not on the phone. Thus, it makes sense that when you had a z-index of 50, it worked flawlessly.

![image](https://github.com/user-attachments/assets/8c39523c-10b8-4d2b-857d-3fdf97f5c7f5)

**Comment by ildar170975** [comment]
> the card-mod creates a new ha-card HTML container that has the z-index set to what you ask in the code

Not exactly, card-mod does create additional elements called “card-mod”; in this particular case card-mod merely set a “z-index” property to the existing “ha-card” element. And this “ha-card” element is a part of mod-card (a wrapper card). Since mod-card is a part of card-mod plugin - you are saying that “this ha-card was created by card-mod” which is not correct technically. 

> However inside this ha-card is the restriction card AND the card that should be restricted, so by inheritance, both will have the same z-index value.

The card-mod solution in Readme is for another case:
1. There are 2 cards: Entities card with input_select and Restriction card below. 
2. If the Restriction card is locked - it has an “overlay” with some higher “z-index”. 
3. If that “z-index” is higher than for input-select’s dropdown list - then you will not be able to select some options inside this list. 

So it was suggested to play with z-index for Restriction card; I would say this advice became “outdated” and probably should be removed from Readme. 

> also noted in the first post, that 1.2.7 works fine, on both phone and desktop. There you had a z-index of 50.

This caused issues with input_select; and by the moment of a change in Restriction card - issues with changed more-info dialog. That is why “z-index” was changed in code. 

> better-thermostat-ui-card has z-index of 1 or 3 set for certain components (like the plus and minus buttons, see the screenshot below)

Imho it is advisable for custom cards’ developers to play with z-index thoughtlessly.
Check if elements of this card with higher z-index still functional if you changed them by card-mod to ZERO. 
If not functional - then you will have to increase a z-index for Restriction card (“overlay” element) to smth like “4” (and check if this change breaks more-info cards and input-select).

**Comment by treitlis** [comment]
OK, I see.

Sorry I am really not familiar with HTML and CSS, but I wonder how hard would be to implement an option in the restriction-card to set the z-index in with a YAML parameter when we configure the card? I mean leave the default to 1 as it is now, but if possible have a z-index option. Mod-card doesn't do this trick for me, because as the card-mod readme says:

> If the simplest form, STYLES is a string of [CSS](https://www.w3schools.com/css/) which will be injected into the ha-card element of the card.

And the restriction-card overlay is not a ha-card, thus my solution is in fact to change the z-index of the card within the restriction-card. This might have unintended consequences, as you also highlighted.

For me it works if I change the z-index of the better thermostat-ui-card to zero, but I don't know if in certain situations, this wouldn't cause some problems. So far I didn't notice any issue.

**Comment by ildar170975** [comment]
Try smth like this:
```
  - type: custom:mod-card
    card:
      type: custom:restriction-card
      ...
      card:
        ...
    card_mod:
      style:
        restriction-card:
          $: |
            div#overlay {
              z-index: 4;
            }
```

**Comment by treitlis** [comment]
Hi,

Thank you very much for your help, The first solution does the trick. I didn't know that you can change the style of the overlay by using this type of syntax in  the card-mod. 

Thanks again for your help.

**Comment by ildar170975** [comment]
Assume we can close the issue since this is about a custom card with unusual `z-index`.

**Comment by Lecso11** [comment]
Hi! I can't implement the Z index fix for my thermostat card. Changing the Z index does not change anything. This is my thermostat card with the restriction card:
```
type: custom:restriction-card
restrictions:
  confirm:
    text: Felold?
duration: 30
card:
  type: custom:better-thermostat-ui-card
  entity: climate.heater
  name: Lakás
  eco_temperature: 21
  disable_summer: false
  disable_eco: false
  disable_heat: true
  disable_off: true
  disable_menu: false
  disable_battery_warning: false
  set_current_as_main: false
  disable_buttons: false
```
Can someone help?
