### ISSUE TITLE
Hide and Move Lock Icon Card

### ISSUE THREAD

**Issue by N0edL** [iantrich/restriction-card#120]
Hey i want to only show the lock icon when its blocked and how can i move the icon to the right and add some more padding to it?

_Card_
```
type: custom:restriction-card
card:
  type: custom:button-card
  template: light_3
  entity: switch.sonoff_1001eb7762_1
  icon: mdi:ceiling-light
restrictions:
  block:
    condition:
      value: "off"
      entity: script.rolluiken_bediening
```

_Picture_
![image](https://github.com/user-attachments/assets/43ce43bf-9df9-4d6f-9101-350cf974bb58)

**Comment by ildar170975** [comment]
You are asking a question, not reporting a bug or proposing a feature request. Please ask all questions in the dedicated thread - https://community.home-assistant.io/t/lovelace-restriction-card-client-side-security/142889.

If you only need a "block" functionality - then use same condition for "lock":
```
    condition:
      entity: script.rolluiken_bediening
      value: "off"
    restrictions:
      block:
        condition:
          entity: script.rolluiken_bediening
          value: "off"
```
Thee vars described here - https://github.com/iantrich/restriction-card?tab=readme-ov-file#theme-variables.
Please ask all further questions about using these vars in the mentioned Community thread.
