### ISSUE TITLE
1.2.10 and after doesn't work with firefox

### ISSUE THREAD

**Issue by szerencl** [iantrich/restriction-card#130]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**1.2.10, 1.2.11

**Last working release (if known):**1.2.9

**Browser and Operating System:**Firefox 134.0, Win10

**Description of problem:**
In chrome and the android app the card seems to be working as expected, but in firefox it doesn't work (cleared cache).

With a regular restriction card the lock doesn't have to be removed before using the card (in this example, the light can be toggled without removing the lock).
And the restriction card doesn't work at all with `custom:restriction-card`.
![kép](https://github.com/user-attachments/assets/868ac283-4e14-42f8-b5aa-00d6f415e3a3)
```
type: vertical-stack
cards:
  - card:
      entity: light.athom_smart_bulb_7w
    restrictions:
      confirm: true
    type: custom:restriction-card
    row: true
  - type: custom:hui-entities-card
    entities:
      - card:
          entity: light.athom_smart_bulb_7w
        restrictions:
          confirm: true
        type: custom:restriction-card
        row: true
      - entity: light.athom_smart_bulb_7w

```

**Comment by ildar170975** [comment]
> And the restriction card doesn't work at all with custom:restriction-card.

Could you explain?

> regular restriction card

What is a "regular restriction card"?

> but in firefox it doesn't work

This seems to be an issue in FF, caused by removal `display: block` from `:host`:
![image](https://github.com/user-attachments/assets/7b0f61de-824b-4d9b-810f-3559d7568466)
Will see if there is a workaround for this.

---

Other remarks:

> row: true

This option is supposed to be used ONLY in Entities card.

> type: custom:hui-entities-card

Why not using a normal `type: entities`?

**Comment by szerencl** [comment]
> Could you explain?

It's like a regular card, there is no restriction whatsoever.

> What is a "regular restriction card"?

I meant when used in itself not in an entities stack. See my example.
```
  - card:
      entity: light.athom_smart_bulb_7w
    restrictions:
      confirm: true
    type: custom:restriction-card
```



> Why not using a normal `type: entities`?

> This option is supposed to be used ONLY in Entities card.

I took the example code from the README on github for testing. However I tried with both entities card and without the row option, but it had no effect.

The example code:
```
type: 'custom:hui-entities-card'
entities:
  - card:
      entity: cover.garage_door
    restrictions:
      block: true
    type: 'custom:restriction-card'
    row: true
  - entity: light.kitchen
```

**Comment by ildar170975** [comment]
FYI this is a simple test case:
```
type: custom:restriction-card
card:
  type: entities
  entities:
    - sun.sun
```
![image](https://github.com/user-attachments/assets/6aeeebd4-3d98-485a-9799-df272cfb412f)
where the "lock" icon is misplaced.

Happens in FF only.
Even an iOS Companion app on an ancient iPhone 5S (iOS 12.5.x) shows it normally.

> However I tried with both entities card and without the row option, but it had no effect.

Absolutely, ANY code with `restriction-card` seems to be operating differently in FF.
Will see how to fix it.

> I took the example code from the README

OMG, this is an ancient code, will replace it with a stock Entities card.
![image](https://github.com/user-attachments/assets/389d7139-e48a-4cb4-89ab-c4a520d17eaa)
