### ISSUE TITLE
restriction-card inside popup-card not working

### ISSUE THREAD

**Issue by Nisbo** [iantrich/restriction-card#141]
The restriction-card itself is working.
If I put it in a popup-card it is working in the editor, I can see the input mask and I can unlock the card.

![Image](https://github.com/user-attachments/assets/6a805ae6-7236-4509-b6ab-aed8c815f6f6)

But the input mask is not shown in the dashboard outside the editor mode.

I click on the button, the popup-card is shown and I can see the small lock on the top left

![Image](https://github.com/user-attachments/assets/50a42c30-97b5-45dd-ad7c-950b397a1b9d)

But if I click on a button nothing happens

```
type: custom:popup-card
title: Kamera Recording Status
dismissable: true
entity: camera.flur
size: normal
card:
  type: custom:restriction-card
  restrictions:
    pin:
      code: 1234
  card:
    type: entities
    entities:
      - entity: input_button.kameras_ein
        name: Alle Kameras EIN
      - entity: input_button.kameras_aus
        name: Alle Kameras AUS
        secondary_info: none
      - entity: select.uvc_g3_flex_2_az_recording_mode
        name: Arbeitszimmer - Regal
      - entity: select.g3_flex_recording_mode_3
        name: Arbeitszimmer - Schrank
      - entity: select.g3_flex_recording_mode_2
        name: Flur
      - entity: select.uvc_g3_flur_recording_mode
        name: Katzenfutter
        secondary_info: none
      - entity: select.uvc_g3_flex_1_kuche_recording_mode
        name: Küche
      - entity: select.uvc_g4_instant_wz_recording_mode
        name: Wohnzimmer - Links
      - entity: select.g4_instant_recording_mode
        name: Wohnzimmer - Rechts
      - entity: select.g3_instant_recording_mode
        name: Wohnzimmer - Kratzbaum
      - entity: select.g3_flex_recording_mode
        name: Straße
```

Any ideas ?

**Comment by ildar170975** [comment]
> But the input mask is not shown in the dashboard outside the editor mode.

What is "input mask"?

**Comment by Nisbo** [comment]
The key pad "input pin Code" 
As shown on the 1st Screenshot

**Comment by ildar170975** [comment]
Does it work with stock cards like Entities card?

**Comment by Nisbo** [comment]
Yes. If I use it without the popup card its working
```
  type: custom:restriction-card
  restrictions:
    pin:
      code: 1234
  card:
    type: entities
    entities:
      - entity: input_button.kameras_ein
        name: Alle Kameras EIN
      - entity: input_button.kameras_aus
        name: Alle Kameras AUS
        secondary_info: none
      - entity: select.uvc_g3_flex_2_az_recording_mode
        name: Arbeitszimmer - Regal
      - entity: select.g3_flex_recording_mode_3
        name: Arbeitszimmer - Schrank
      - entity: select.g3_flex_recording_mode_2
        name: Flur
      - entity: select.uvc_g3_flur_recording_mode
        name: Katzenfutter
        secondary_info: none
      - entity: select.uvc_g3_flex_1_kuche_recording_mode
        name: Küche
      - entity: select.uvc_g4_instant_wz_recording_mode
        name: Wohnzimmer - Links
      - entity: select.g4_instant_recording_mode
        name: Wohnzimmer - Rechts
      - entity: select.g3_instant_recording_mode
        name: Wohnzimmer - Kratzbaum
      - entity: select.g3_flex_recording_mode
        name: Straße

```

**Comment by Nisbo** [comment]
OK, the problem is more complicated than expected. ^^ Sorry for the long text / code
FYI: The code above was in a plain dashboard.

In my wall panel dashboard, I am using a lot of different cards.

### 1
If I am using it in a `custom:vertical-stack-in-card`  with a `type: entity` its working. But I need an other card for styling and sripting

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:restriction-card
    restrictions:
      pin:
        code: 1234
    card:
      type: entity
      entity: input_boolean.popupcardbutton
      tap_action:
        action: more-info
```


### 2
If I am using it in a `custom:vertical-stack-in-card`  with a `type: custom:button-card` it is partially working.
It only works if I click on the red marked part of the button. If I click outside it doesnt ask for the code and opens the popup card.

![Image](https://github.com/user-attachments/assets/11a21269-8c98-4901-bb00-582d645c68c0)

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:restriction-card
    restrictions:
      pin:
        code: 1234
    card:
      type: custom:button-card
      template: base
      entity: input_boolean.popupcardbutton
      name: |
        [[[
         if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' &&
            states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' &&
            states['select.g3_flex_recording_mode_3'].state === 'Never' &&
            states['select.g3_flex_recording_mode_2'].state === 'Never' &&
            states['select.uvc_g3_flur_recording_mode'].state === 'Never' &&
            states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' &&
            states['select.g4_instant_recording_mode'].state === 'Never') {
           return 'Aufnahme aus';
         } else if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' ||
                  states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' ||
                  states['select.g3_flex_recording_mode_3'].state === 'Never' ||
                  states['select.g3_flex_recording_mode_2'].state === 'Never' ||
                  states['select.uvc_g3_flur_recording_mode'].state === 'Never' ||
                  states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' ||
                  states['select.g4_instant_recording_mode'].state === 'Never') {
           return 'Aufnahme teilweise aus';
         } else {
           return 'Aufnahme ein';
         }
        ]]]
      size: 120%
      show_state: false
      aspect_ratio: 1/1
      styles:
        icon:
         - position: relative
         - left: 1.0rem
         - top: 1.0rem
         - color: >
            [[[ if (states['select.uvc_g4_instant_wz_recording_mode'].state ===
            'Never' &&
               states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' &&
               states['select.g3_flex_recording_mode_3'].state === 'Never' &&
               states['select.g3_flex_recording_mode_2'].state === 'Never' &&
               states['select.uvc_g3_flur_recording_mode'].state === 'Never' &&
               states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' &&
               states['select.g4_instant_recording_mode'].state === 'Never') {
              return 'rgb(235, 0, 0)';  // Rot für 'Aufnahme aus'
            } else if (states['select.uvc_g4_instant_wz_recording_mode'].state ===
            'Never' ||
                     states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' ||
                     states['select.g3_flex_recording_mode_3'].state === 'Never' ||
                     states['select.g3_flex_recording_mode_2'].state === 'Never' ||
                     states['select.uvc_g3_flur_recording_mode'].state === 'Never' ||
                     states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never') {
              return 'orange';  // Orange für 'Aufnahme teilweise aus'
            } else {
              return 'green';  // Grün für 'Aufnahme ein'
            } ]]]
      icon: |
        [[[
         if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' &&
            states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' &&
            states['select.g3_flex_recording_mode_3'].state === 'Never' &&
            states['select.g3_flex_recording_mode_2'].state === 'Never' &&
            states['select.uvc_g3_flur_recording_mode'].state === 'Never' &&
            states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' &&
            states['select.g4_instant_recording_mode'].state === 'Never') {
           return 'phu:camera-nomotion';  // Symbol für 'Aufnahme aus'
         } else if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' ||
                  states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' ||
                  states['select.g3_flex_recording_mode_3'].state === 'Never' ||
                  states['select.g3_flex_recording_mode_2'].state === 'Never' ||
                  states['select.uvc_g3_flur_recording_mode'].state === 'Never' ||
                  states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never') {
           return 'phu:camera-nomotion';  // Symbol für 'Aufnahme teilweise aus'
         } else {
           return 'phu:camera-person';  // Symbol für 'Aufnahme ein'
         }
        ]]]
      tap_action:
        action: more-info
```



### 3
If I put the restriction-card inside the popup-card (the same than in my 1st post)

```
type: custom:popup-card
title: Kamera Recording Status
dismissable: true
entity: input_boolean.popupcardbutton
size: normal
card:
  type: custom:restriction-card
  restrictions:
    pin:
      code: 1234
  card:
    type: entities
    entities:
      - entity: input_button.kameras_ein
        name: Alle Kameras EIN
      - entity: input_button.kameras_aus
        name: Alle Kameras AUS
        secondary_info: none
      - entity: select.uvc_g3_flex_2_az_recording_mode
        name: Arbeitszimmer - Regal
      - entity: select.g3_flex_recording_mode_3
        name: Arbeitszimmer - Schrank
      - entity: select.g3_flex_recording_mode_2
        name: Flur
      - entity: select.uvc_g3_flur_recording_mode
        name: Katzenfutter
        secondary_info: none
      - entity: select.uvc_g3_flex_1_kuche_recording_mode
        name: Küche
      - entity: select.uvc_g4_instant_wz_recording_mode
        name: Wohnzimmer - Links
      - entity: select.g4_instant_recording_mode
        name: Wohnzimmer - Rechts
      - entity: select.g3_instant_recording_mode
        name: Wohnzimmer - Kratzbaum
      - entity: select.g3_flex_recording_mode
        name: Straße

```
and use a `custom:vertical-stack-in-card`  with a `type: custom:button-card` to open the popupcard, it is not working.

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:button-card
    template: base
    entity: input_boolean.popupcardbutton
    name: |
      [[[
       if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' &&
          states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' &&
          states['select.g3_flex_recording_mode_3'].state === 'Never' &&
          states['select.g3_flex_recording_mode_2'].state === 'Never' &&
          states['select.uvc_g3_flur_recording_mode'].state === 'Never' &&
          states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' &&
          states['select.g4_instant_recording_mode'].state === 'Never') {
         return 'Aufnahme aus';
       } else if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' ||
                states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' ||
                states['select.g3_flex_recording_mode_3'].state === 'Never' ||
                states['select.g3_flex_recording_mode_2'].state === 'Never' ||
                states['select.uvc_g3_flur_recording_mode'].state === 'Never' ||
                states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' ||
                states['select.g4_instant_recording_mode'].state === 'Never') {
         return 'Aufnahme teilweise aus';
       } else {
         return 'Aufnahme ein';
       }
      ]]]
    size: 120%
    show_state: false
    aspect_ratio: 1/1
    styles:
      icon:
        - position: relative
        - left: 1.0rem
        - top: 1.0rem
        - color: >
            [[[ if (states['select.uvc_g4_instant_wz_recording_mode'].state ===
            'Never' &&
               states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' &&
               states['select.g3_flex_recording_mode_3'].state === 'Never' &&
               states['select.g3_flex_recording_mode_2'].state === 'Never' &&
               states['select.uvc_g3_flur_recording_mode'].state === 'Never' &&
               states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' &&
               states['select.g4_instant_recording_mode'].state === 'Never') {
              return 'rgb(235, 0, 0)';  // Rot für 'Aufnahme aus'
            } else if (states['select.uvc_g4_instant_wz_recording_mode'].state
            === 'Never' ||
                     states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' ||
                     states['select.g3_flex_recording_mode_3'].state === 'Never' ||
                     states['select.g3_flex_recording_mode_2'].state === 'Never' ||
                     states['select.uvc_g3_flur_recording_mode'].state === 'Never' ||
                     states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never') {
              return 'orange';  // Orange für 'Aufnahme teilweise aus'
            } else {
              return 'green';  // Grün für 'Aufnahme ein'
            } ]]]
    icon: |
      [[[
       if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' &&
          states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' &&
          states['select.g3_flex_recording_mode_3'].state === 'Never' &&
          states['select.g3_flex_recording_mode_2'].state === 'Never' &&
          states['select.uvc_g3_flur_recording_mode'].state === 'Never' &&
          states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never' &&
          states['select.g4_instant_recording_mode'].state === 'Never') {
         return 'phu:camera-nomotion';  // Symbol für 'Aufnahme aus'
       } else if (states['select.uvc_g4_instant_wz_recording_mode'].state === 'Never' ||
                states['select.uvc_g3_flex_2_az_recording_mode'].state === 'Never' ||
                states['select.g3_flex_recording_mode_3'].state === 'Never' ||
                states['select.g3_flex_recording_mode_2'].state === 'Never' ||
                states['select.uvc_g3_flur_recording_mode'].state === 'Never' ||
                states['select.uvc_g3_flex_1_kuche_recording_mode'].state === 'Never') {
         return 'phu:camera-nomotion';  // Symbol für 'Aufnahme teilweise aus'
       } else {
         return 'phu:camera-person';  // Symbol für 'Aufnahme ein'
       }
      ]]]
    tap_action:
      action: more-info
```
as said in my 1st post, nothing happens. It doesnt ask for the pin and I can not change anything on the card.

So I assume its somehow related to the `custom:button-card`. 

There are no errors for the restriction-card in the logger (F12)

PS: Home Assistant is on version 2024.12.5 (dont want to update till the encrypted backup issue is fixed)
