### ISSUE TITLE
Can not enter alphanumeric pin in Home Assistant app on android

### ISSUE THREAD

**Issue by StefanGit22** [iantrich/restriction-card#143]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** latest (1.2.15)

**Last working release (if known):** 1.2.13

**Browser and Operating System:** Android 15, Home Assistant app

**Description of problem:**

Since the update of the restriction cart to 1.2.15 i can no longer enter an alphanumeric pin in the Home Assistant app on an android 15 smartphone.
I have set my code to a more secure alphanumerikal code (eg. 12a@) but since 1.2.15 i can no longer input my set code because the app only offers me a numbers keyboard (and the numbers touch field).

I can not find an option to get the old behavior back and i would like to keep my more secure code (on PC it´s not an issue becouse i have my normal keyboard).

Mabey this could be an option in the pin options to either use only numbers, then the new input should be shown or use the old input if you want to use more than numbers. 

**My Card Config:**

```
type: custom:restriction-card
restrictions:
  confirm: null
  pin:
    code: 1@23
card:
  type: button
  show_name: true
  show_icon: true
  tap_action:
    action: toggle
  entity: lock.haustur
  hold_action:
    action: none

```
