### ISSUE TITLE
[Bug] Restriction card with versatile_thermostat_ui_card

### ISSUE THREAD

**Issue by inrepublica** [iantrich/restriction-card#144]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.2.15

**Browser and Operating System:**
Windows 11 and firefox 135 or Chrome 133

**Description of problem:**
When I use restriction-card with [versatile_thermostat-ui-card](https://github.com/jmcollin78/versatile-thermostat-ui-card) the restriction doesn't work for me...
I use this yaml for the card:
```yaml
type: custom:restriction-card
card:
  type: custom:versatile-thermostat-ui-card
  entity: climate.piece_principale
  name: Pièce Principale
```

The native thermostat card works like a charm.
On the left native thermostat card and on the right versatile_thermostat-ui-card:

![Image](https://github.com/user-attachments/assets/c154069c-fc57-4cc3-8fa0-a30594b6e133)

**Additional information:**

**Comment by ildar170975** [comment]
Let me know if it is same. 
https://github.com/iantrich/restriction-card/issues/119

**Comment by inrepublica** [comment]
Thanks for your replie, It looks like the problems are the same.

I've trying this yaml but the problem persist:
```yaml
type: custom:restriction-card
card:
  type: custom:versatile-thermostat-ui-card
  entity: climate.piece_principale
  name: Pièce Principale
  card_mod:
    style: |
      ha-card {
         z-index: 0;
        }
```

**Comment by inrepublica** [comment]
In the source code of versatile-thermostat-ui-card i have found this code:
```yaml
 .more-info {
        position: absolute;
        cursor: pointer;
        top: 0px;
        right: 0px;
        inset-inline-end: 0px;
        inset-inline-start: initial;
        border-radius: 100%;
        color: var(--secondary-text-color);
        z-index: 1;
        direction: var(--direction);
```
