### ISSUE TITLE
Duration reached feedback missing in case of hold action

### ISSUE THREAD

**Issue by schnillerman** [iantrich/restriction-card#158]
**Is your feature request related to a problem? Please describe.**
If duration for hold action is set to a value, one can never know if the duration is reached and the lock is open. I usually end up trying several times before the row gets unlocked.

**Describe the solution you'd like**
If a duration for unlocking an, e.g., row with a toggle is defined, a vibration or color change of the lock or both as soon as the duration is reached would be nice.

**Describe alternatives you've considered**
N/A

**Additional context**
Example script:
```
type: entities
title: Macchina Caffè
entities:
  - type: custom:restriction-card
    row: true
    duration: 5
    action: hold
    card:
      entity: switch.macchina_caffe
    state_color: true
  - entity: script.sveglia_macchina_caffe
```
