### ISSUE TITLE
Entities card row goes blank with condition options set.

### ISSUE THREAD

**Issue by ZoeyPhoenix** [iantrich/restriction-card#159]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.2.19 (used Hacs to install latest version)

**Last working release (if known):**
Just installed, haven't used this until now.

**Browser and Operating System:**

Issue effects both -

Windows 10 22H2 - Firefox 136.0.1 (64-bit)
Android 12 -  Home Assistant Companion app 2025.1.2-full

**Description of problem:**

Hello, 

When adding options under condition: the card goes blank, and cannot be interacted with.
In the below screenshot, there should be two entities displayed but there is only one.

![Image](https://github.com/user-attachments/assets/eea9254f-caed-46ff-b51b-730c6718493d)

```yaml
type: entities
show_header_toggle: false
entities:

  - type: custom:restriction-card
    row: true
    condition:
      entitiy: switch.s31_4_sonoff_s31_relay
      value: "on"
    restrictions:
      confirm:
        text: Switch is ON! Are you sure!?
    card:
      entity: switch.s31_4_sonoff_s31_relay
      
  - type: custom:restriction-card
    row: true
    restrictions:
      confirm:
        text: Switch is ON! Are you sure!?
    card:
      entity: switch.s31_4_sonoff_s31_relay
```

**Javascript errors shown in the web inspector (if applicable):**

```
caught (in promise) TypeError: t is undefined
    Mt http://homeassistant.local:8123/hacsfiles/restriction-card/restriction-card.js?hacstag=2156334041219:200
    render http://homeassistant.local:8123/hacsfiles/restriction-card/restriction-card.js?hacstag=2156334041219:202
    update http://homeassistant.local:8123/hacsfiles/restriction-card/restriction-card.js?hacstag=2156334041219:186
    performUpdate http://homeassistant.local:8123/hacsfiles/restriction-card/restriction-card.js?hacstag=2156334041219:148
    _enqueueUpdate http://homeassistant.local:8123/hacsfiles/restriction-card/restriction-card.js?hacstag=2156334041219:148
[restriction-card.js:200:5809](http://homeassistant.local:8123/hacsfiles/restriction-card/restriction-card.js?hacstag=2156334041219)
```

**Additional information:**
