### ISSUE TITLE
Restriction not working on thermostat cards

### ISSUE THREAD

**Issue by Lecso11** [iantrich/restriction-card#160]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2025.3.4
**Last working release (if known):**

**Browser and Operating System:**
Firefox on Windows and Android companion app

**Description of problem:**

The restriction does not work if I move the dot of the thermostat ring or press the - and + on the thermostat card. When clicking on the card somewhere else, the restriction popup shows up.
These are the cards:
```
type: custom:restriction-card
restrictions:
  confirm:
    text: Felold?
duration: 30
card:
  type: custom:better-thermostat-ui-card
  entity: climate.heater
  name: Lakás
  eco_temperature: 21
  disable_summer: false
  disable_eco: false
  disable_heat: true
  disable_off: true
  disable_menu: false
  disable_battery_warning: false
  set_current_as_main: false
  disable_buttons: false
```
```
type: custom:restriction-card
restrictions:
  confirm:
    text: Felold?
duration: 30
card:
  type: custom:better-thermostat-ui-card
  entity: climate.bedroom_radiator
  name: Hálószoba
  eco_temperature: 21
  disable_buttons: false
  set_current_as_main: false
  disable_battery_warning: false
  disable_menu: false
  disable_off: true
  disable_heat: true
  disable_summer: true
  disable_window: true
  disable_eco: true
```
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
