### ISSUE TITLE
action is ignored when confirm: text: is used....

### ISSUE THREAD

**Issue by quinnmjcj** [iantrich/restriction-card#165]
I have confirm: text:  type unlock - I would like it to not show the text until the user has done the action - now it always does it on first tap. I'd like for double-tap or hold to be required to show the confirmation if I've set that as the action.

**Comment by ildar170975** [comment]
Please post a short code demonstrating your issue & some explanations. Currently it is unclear.
If you are asking for a confirmation popup AFTER you did something - this is not following HA guidelines.

**Comment by quinnmjcj** [comment]
```
type: custom:restriction-card
restrictions:
  action: double_tap
  confirm:
    text: Unlock?
card:
  type: entities
  entities:
    - cover.msg100_16a4_garage_door
    - sensor.garage_status
  state_color: true
```

Would like it to require a double-tap to get the confirm message - right now, a single tap always brings up the confirm message.  Same for hold - require hold to bring up the confirm message....  That way a gratuitous tap doesn't bring up the message - just a little more assurance you want to unlock.

**Comment by ildar170975** [comment]
Please format your code, it is unreadable. Check other issues for comparison.

**Comment by quinnmjcj** [comment]
Just FYI - it's formatted when I edit it - (I copy/pasted it out of the yaml editor of HA). it changes when I save it - must be a markdown thing   Saw the "code" edit and tried that and that seems to fix it.

**Comment by ildar170975** [comment]
To format a code, place it into triple "`".

Now I see - you placed `action` into a wrong place.
Note that a default value is "tap".
Try this:
```
type: custom:restriction-card
action: double_tap
restrictions:
  confirm:
    text: Unlock?
card:
  ...
```
