### ISSUE TITLE
Unknown type encountered: entities

### ISSUE THREAD

**Issue by SeLLeRoNe** [iantrich/restriction-card#18]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.1.9
**Last working release (if known):**
1.1.8
**Browser and Operating System:**
Chgrome on Windows 10

**Description of problem:**
Since last update my restricted cards (type: entities) are no longer working, but if I don't specify the "type" they do work.

Not really sure this was intended or not, haven't seen anything on the release note that would introduce a breaking change.

Here my card-config:
```
          - type: entities
            show_header_toggle: false
            entities:
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
#                  type: entities
                  name: Fridge
                  entity: switch.fridge
                  state_color: true
                  tap_action:
                    action: none
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  type: entities
                  name: Dishwasher
                  entity: switch.dishwasher
                  state_color: true
                  tap_action:
                    action: none
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  type: entities
                  name: Toaster
                  entity: switch.toaster
                  state_color: true
                  tap_action:
                    action: none
```

Here how it looks:
![image](https://user-images.githubusercontent.com/9599441/77192235-89795100-6adc-11ea-94b4-b73bc6592b3c.png)

**Javascript errors shown in the web inspector (if applicable):**

```
No console error apparently, sorry
```

**Additional information:**

**Comment by iantrich** [comment]
`entities` is not a valid row type. you can try `custom:hui-entities-card`

**Comment by SeLLeRoNe** [comment]
Oh okay,I through it was a bug since it was working with the previous version :)

Thanks

**Comment by iantrich** [comment]
it was more so an error on my part previously

**Comment by SeLLeRoNe** [comment]
Sorry to bother again, I did update HA this morning and now the entities needs to be in an array, which is fair enough, but the outcome is "ugly" somehow
```
          - type: entities
            show_header_toggle: false
            entities:
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  type: custom:hui-entities-card
                  name: Fridge
                  entities:
                    - entity: switch.fridge
                      state_color: true
                      tap_action:
                        action: none
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  type: custom:hui-entities-card
                  name: Dishwasher
                  entity: switch.dishwasher
                  state_color: true
                  tap_action:
                    action: none
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  type: custom:hui-entities-card
                  name: Toaster
                  entity: switch.toaster
                  state_color: true
                  tap_action:
                    action: none
```
![image](https://user-images.githubusercontent.com/9599441/77227818-31e1f080-6b83-11ea-91da-7be7ac5d1669.png)


The first is the attempt to fix using the code as expected, the second and third are not yet fixed for that requirement, but as you can see the one fixed has the lock "miss-aligned" to the row.

Please let me know if you want me to open an issue just for this or if it's fine to re-open this one :)

Thanks again
Andrea

**Comment by iantrich** [comment]
That's not how you define an entitites card, but also, I'm not sure why you're using the entities row to begin with when you're already in an entities card?

my suggestion
```yaml
          - type: entities
            show_header_toggle: false
            state_color: true
            entities:
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  name: Fridge
                  entity: switch.fridge
                  tap_action:
                    action: none
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  type: custom:hui-entities-card
                  name: Dishwasher
                  entity: switch.dishwasher
                  tap_action:
                    action: none
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                row: true
                card:
                  name: Toaster
                  entity: switch.toaster
                  tap_action:
                    action: none
```
