### ISSUE TITLE
unused entities shows entities with restriction-card type

### ISSUE THREAD

**Issue by Thuurke** [iantrich/restriction-card#21]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
HA 0.107.5
Restricted-card 1.1.9

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
I use the restriction-card. When an entity is used as in below code the unused entites list still shows the entity. 

```
        entities:
          - card:
              entity: automation.available_ikea_lag14_01
            restrictions:
              block: true
            type: custom:restriction-card
            row: true
```
If I replace above code by
```
        entities:
          - entity: automation.available_ikea_lag14_01
```
the entity is not listed in the unused entities

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
