### ISSUE TITLE
Change "condition" to "conditions" allowing multiple conditions

### ISSUE THREAD

**Issue by SeLLeRoNe** [iantrich/restriction-card#22]
**Is your feature request related to a problem? Please describe.**
I would like to block the washing machine plug if the washing machine is in one of the active states, such as Washing, Drying, Warming Up and the ability to define  the restriction type based on that.
(ex. fully restricted if the condition are met, half restricted (double click) if they are not.

**Describe the solution you'd like**
Having the ability to select multiple condition would allow more control and flexibility:

**Describe alternatives you've considered**
Using input_boolean with automations to define if the washing machine is "working" or not.

**Additional context**

Code sample:
```
          - type: entities
            show_header_toggle: false
            entities:
              - type: "custom:restriction-card"
                restrictions:
                  block: true
                conditions:
                  - entity: input_select.washing_machine_status
                    value: "Warming Up"
                  - entity: input_select.washing_machine_status
                    value: "Washing"
                  - entity: input_select.washing_machine_status
                    value: "Drying"
                row: true
                card:
                  name: Washing Machine
                  entity: switch.washing_machine
                  state_color: true
                  tap_action:
                    action: none

```

Hope this is clear enough, thanks :)
