### ISSUE TITLE
Lock icon height/width options do not work properly with rows

### ISSUE THREAD

**Issue by Anwen747** [iantrich/restriction-card#23]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:** 1.1.9

**Last working release (if known):** unknown

**Browser and Operating System:**  Chrome on Windows 10 PC.  Running HA Supervised 0.106.5 on Ubuntu 18.04 host on a NUC.  (Cannot move to 0.107.x until z-wave issues are fixed.)

Google Chrome is up to date
Version 80.0.3987.149 (Official Build) (64-bit)

**Description of problem:**

Changing the lock height/width via my theme does not work.  The lock icon does not increase in size, instead it simply moves down.

in my theme:
```
  restriction-lock-row-margin-left: 95%
  restriction-lock-icon-height: 60px
  restriction-lock-icon-width: 60px
  restriction-regular-lock-color: "#FFFFFF"
```

In my Lovelace view:

```
      - type: entities
        title: Lighting Groups
        show_header_toggle: false
        entities:
          - card:
              entity: light.dark_early_lights
              icon: mdi:lightbulb-on
            type: "custom:restriction-card"
            row: true
            
          - card:
              entity: light.all_house_lights
              icon: mdi:lightbulb-multiple
            type: "custom:restriction-card"
            row: true
```
Screenshots:

Without setting height/width in theme:

![locksorig](https://user-images.githubusercontent.com/51857150/77921890-510d0c00-726e-11ea-9b00-078b1b6eb088.JPG)

With height/width set in theme as above:

![switchlocks](https://user-images.githubusercontent.com/51857150/77921989-74d05200-726e-11ea-86c6-048405384bb5.JPG)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Not sure if this is helpful, but the following are installed:

BROWSER_MOD 1.0.1 IS INSTALLED
card-tools.js:1 CARD-TOOLS 2.1.2 IS INSTALLED
restriction-card.js:200   RESTRICTION-CARD    Version 1.1.9     
custom-header.js:145   CUSTOM-HEADER    Version 1.3.2  
simple-thermostat.js:1 simple-thermostat: 0.34.0
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.9.3 
fold-entity-row.js:46 FOLD-ENTITY-ROW 1.0.1 IS INSTALLED
