### ISSUE TITLE
State color doesn't work when applying restriction-card

### ISSUE THREAD

**Issue by LiquidBlackNL** [iantrich/restriction-card#24]
**Checklist:**

- [HA 0.107.7 & Addon v1.1.9] I updated to the latest version available
- [Yes] I cleared the cache of my browser

**Release with the issue:** v1.1.9

**Last working release (if known):** unknow

**Browser and Operating System:**
Google Chrome v80.0.3987.163 64-bit - Win10 v1903
Google Chrome Android 10 v80.0.3987.162 - OnePlus 6 OxygenOS v10.3.2

**Description of problem:**

"state_color: true" is not working when using restriction-card. 
State_color works again with same sensors when not using restriction-card.

LoveLace:
![2020-04-07 12_23_37-Window](https://user-images.githubusercontent.com/50137101/78658668-bdb98380-78ca-11ea-9aaa-2db146b493df.png)

```
entities:
  - card:
      entity: cover.garage_poort
    restrictions:
      confirm: true
    row: true
    type: 'custom:restriction-card'
  - entity: sensor.garage_poort_beweging
show_header_toggle: false
state_color: true
title: Garage
type: 'custom:hui-entities-card'
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Installed add-ons:
Duck DNS
File Editor
Hass.io Google Drive Backup
Log Viewer
Mosquitto broker
Node-RED
Samba share
Terminal & SSH
Zigbee2Mqtt

HACS:
ZiggoNext
Lovelace Swipe Navigation
Restriction Card

**Comment by iantrich** [comment]
Add to the row’s config

```
entities:
  - card:
      entity: cover.garage_poort
      state_color: true
```
