### ISSUE TITLE
Stack cards?

### ISSUE THREAD

**Issue by Meesen0743** [iantrich/restriction-card#31]
Is it possible to implement restrictions to "Stack cards"? & If so is there any documentation 

Apologies if this is something that already exists, I have searched but found no answers.

Thanks,
Meesen0743

**Comment by iantrich** [comment]
Docs would be no different really. The card would be your stack
```yaml
type: custom:restriction-card
card:
  type: vertical-stack
  cards:
  ...etc
```
