### ISSUE TITLE
Double_tap action to unlock doesn't seem to work after last update

### ISSUE THREAD

**Issue by pplucky** [iantrich/restriction-card#38]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser / tried in anonymous mode

**Release with the issue:**
1.2.5

**Last working release (if known):**
1.1.9 (maybe later, but I upgraded from 1.1.9 to 1.2.5)

**Browser and Operating System:**
Safari Version 13.1 (14609.1.20.111.8) / macOS
Google Chrome Version 83.0.4103.116 (Official Build) (64-bit) / macOS 
Google Chrome Version 79.0.3945.88 (Official Build) (64-bit) / Windows 10

**Description of problem:**
Double_tap action to unlock doesn't seem to work after last update
Tap and hold seem to work just fine, as expected

My Lovelace card config:
```
entities:
  - action: double_tap
    card:
      entity: script.hass_restart
    restrictions:
      confirm:
        text: Are you sure you want to restart HA?
    row: true
    type: 'custom:restriction-card'
  - action: double_tap
    card:
      entity: script.hasspi_reboot
    restrictions:
      confirm:
        text: Are you sure you want to reboot RPi?
    row: true
    type: 'custom:restriction-card'
  - action: double_tap
    card:
      entity: script.hasspi_shutdown
    restrictions:
      confirm:
        text: Are you sure you want to shutdown RPi?
    row: true
    type: 'custom:restriction-card'
show_header_toggle: false
state_color: true
title: System Utils
type: entities
```

Theme:
```
steel:
  primary-color: steelblue

  ### Restrction Card setting
  restriction-lock-row-margin-left: 92%
```

![image](https://user-images.githubusercontent.com/16407309/86374974-73576100-bc85-11ea-8ca2-43d635d3dc02.png)

When I double click, nothing happens, no additional info card, no unlock, nothing...

My HA info:

Frontend version: 20200701.0 - latest

**System Health**
|arch|armv7l|
| --- | --- |
|chassis||
|dev|false|
|docker|true|
|docker_version|19.03.11|
|hassio|true|
|host_os|Raspbian GNU/Linux 10 (buster)|
|installation_type|Home Assistant Supervised|
|os_name|Linux|
|os_version|4.19.118-v7l+|
|python_version|3.7.7|
|supervisor|228|
|timezone|redacted|
|version|0.112.0|
|virtualenv|false|

### Lovelace

|dashboards|3|
| --- | --- |
|mode|storage|
|resources|9|
|views|7|

**Javascript errors shown in the web inspector (if applicable):**
Nothing I could identify

```

```

**Additional information:**
