### ISSUE TITLE
row: boolean is not optional

### ISSUE THREAD

**Issue by shreram** [iantrich/restriction-card#41]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.107-Unraid
python_version | 3.8.3
timezone | America/Chicago
version | 0.114.4
virtualenv | false

**Description of problem:**

Per the documentation, the row is optional but without that, it shows an error.

row | boolean | Optional
-- | -- | --

This issue is the same as https://github.com/iantrich/restriction-card/issues/30

**Javascript errors shown in the web inspector (if applicable):**

```
  - id: e10d515ca2e448cf84727729f4842261  # Automatically created id
    type: conditional
    conditions:
      - entity: input_boolean.show_appdaemon_apps
        state: "on"
    card:
      type: entities
      title: AppDaemon Apps
      show_header_toggle: false
      entities:
        - card:
            entity: input_boolean.ad_dark_house_lights
          type: 'custom:restriction-card'
          # row: true
        - card:
            entity: input_boolean.ad_watch_dog
          type: 'custom:restriction-card'
          row: true
        - card:
            entity: input_boolean.ad_sunset_lights
          type: 'custom:restriction-card'
          row: true
        - card:
            entity: input_boolean.ad_bedtime_lights
          type: 'custom:restriction-card'
          row: true
        - card:
            entity: input_boolean.ad_night_lights
          restrictions:
            block: true
          type: 'custom:restriction-card'
          row: true
        - input_boolean.ad_speed_alerts

```

```
chunk.c136a66895309b59c3fe.js:13138 card undefined Error: No card type configured.
    at d (chunk.c136a66895309b59c3fe.js:13138)
    at l (chunk.c136a66895309b59c3fe.js:13138)
    at Module.Vt (chunk.c136a66895309b59c3fe.js:12159)
    at HTMLElement.renderCard (restriction-card.js:218)
    at HTMLElement.render (restriction-card.js:216)
    at HTMLElement.update (restriction-card.js:186)
    at HTMLElement.performUpdate (restriction-card.js:148)
    at HTMLElement._enqueueUpdate (restriction-card.js:148)
```

**Additional information:**
