### ISSUE TITLE
Lock icon is displayed, but the row is still editable (input_number)

### ISSUE THREAD

**Issue by ildar170975** [iantrich/restriction-card#52]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
Home Assistant 2021.5.5 (in Docker, Ubuntu)
restriction-card 1.2.6

**Last working release (if known):**

**Browser and Operating System:**
Chrome 91.0.4472.77
Win10x64 Pro (20H2)

**Description of problem:**
Steps to reproduce:
1. The row is not editable - slider cannot be changed. The "lock" icon is displayed.
2. Tap on the row.
3. A message box "input pin code" will appear.
4. Input pin 1234.
5. The row becomes editable. The "lock" icon disappears.
6. Start changing the slider; do not stop (do not release a mouse button).
7. After some time the "lock" icon appears again. But the slider still can be changed.
8. Stop changing the slider (release the mouse button).
9. A new value is displayed for the input_number.

Test card:
```
type: 'custom:restriction-card'
restrictions:
  pin:
    code: 1234
card:
  type: entities
  entities:
    - entity: input_number.test_number
```
![image](https://user-images.githubusercontent.com/71872483/120052490-40048a00-c02e-11eb-8df7-bb4fa65a2e2d.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
