### ISSUE TITLE
No state color with state_color: true set on card

### ISSUE THREAD

**Issue by emufan** [iantrich/restriction-card#60]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Description of problem:**

If you use ```state_color: true``` an restrict an entity row, the state color is not shown anymore and always --paper-item-icon-color is set instead of --paper-item-active-icon-color if active and used without restriction.

```
type: entities
entities:
  - type: custom:restriction-card
    row: true
    card:
      entity: cover.rolladen_kinderzimmer
      name: Kinderzimmer
    restrictions:
      confirm:
        text: Schalter aktivieren?
    condition:
      entity: switch.shelly_hausturklingel_klingelstatus
      value: 'off'
state_color: true
```

With restriction card on row
![image](https://user-images.githubusercontent.com/22775515/132830506-d7f49893-92ae-4293-aab3-23c9b6aa6ad1.png)

Without restriction card on row in same state
![image](https://user-images.githubusercontent.com/22775515/132830618-c7e1b5d8-ff15-4513-84c6-4245efa5ef9a.png)

```
type: entities
entities:
  - cover.rolladen_kinderzimmer
state_color: true
```
