### ISSUE TITLE
[FR] Support auto-entities card

### ISSUE THREAD

**Issue by chemelli74** [iantrich/restriction-card#73]
**Is your feature request related to a problem? Please describe.**
Cannot combine restriction-card with [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) card

**Describe the solution you'd like**
Been able to lock a row from a list generated by auto-entities

**Describe alternatives you've considered**
None so far 

**Additional context**

**Comment by chemelli74** [comment]
@iantrich, do you may consider the proposed FR ?

Simone

**Comment by pschmitt** [comment]
To use this card with auto-entities you can leverage `this.entity_id`:

This for example creates a grid of restricted light cards for all you lights: 

```yaml
type: custom:auto-entities
card:
  type: grid
  columns: 3
card_param: cards
filter:
  include:
    - domain: light
      options:
        type: custom:restriction-card
        card:
          type: light
          entity: this.entity_id
  exclude:
    - state: unavailable
    - state: unknown
```

Ref: https://github.com/thomasloven/lovelace-auto-entities#entity-options
