### ISSUE TITLE
Conditional lock on foreign state

### ISSUE THREAD

**Issue by jzielke84** [iantrich/restriction-card#78]
Hi,

I just can not get my head around on how to lock when a state of another object changes:

```yaml
  - type: custom:restriction-card
    restrictions:
      block: |
        [[[
          if (binary_sensor.fenster_arbeitszimmer_iaszone == 'on')
            return 'true';
          return 'false';
        ]]]
    card:
      type: thermostat
      entity: climate.heizung_arbeitszimmer_thermostat
```
What am I doing wrong here?

**Comment by jzielke84** [comment]
OK I finally solved it:

```yaml
type: custom:restriction-card
restrictions:
  block:
    condition:
      entity: binary_sensor.fenster_arbeitszimmer_iaszone
      value: 'on'
```
