### ISSUE TITLE
Follow new "state-*-color" themes vars (HA 2022.12)

### ISSUE THREAD

**Issue by chemelli74** [iantrich/restriction-card#79]
**Is your feature request related to a problem? Please describe.**
After 2022.12 there are new themes colors: "state-*-color".
Card should be updated to reflect those.

**Describe the solution you'd like**
Add the "state-*-color" as default colors.

**Describe alternatives you've considered**
None found

**Additional context**
Current behaviour:

![image](https://user-images.githubusercontent.com/57354320/208304342-c85d67e1-0460-4f7c-b4e6-0f9d24191e86.png)

**Comment by ildar170975** [comment]
How the `restriction-card` is supposed to be updated for new `state-*-color` vars?
These vars are currently used by Entities card, for instance, they have nothing with the `restriction-card`.
Not to mention a fact that these theme vars are NOT officially supported by HA - i.e. "today these vars are present in HA, tomorrow not".

**Comment by chemelli74** [comment]
Using the following code in autoentities:

```
    - entity_id: cover.tapparella_cucina
      state: open
      options:
        secondary_info: position
    - entity_id: cover.tapparella_cucina
      state: open
      options:
        type: custom:restriction-card
        restrictions:
          pin:
            code: 5686
        condition:
          entity: cover.tapparella_cucina
          value: open
        row: true
        card:
          entity: this.entity_id
          secondary_info: position
```

makes the icons color as shown above.
So I would say that colors are not honored by this custom card.
Or am I wrong ?

Simone
