### ISSUE TITLE
The updated version does not work

### ISSUE THREAD

**Issue by ildar170975** [iantrich/restriction-card#92]
Installed the latest 1.2.8 (although Code inspector says 1.2.6)

![image](https://github.com/iantrich/restriction-card/assets/71872483/c86017aa-cedd-4c8d-a13b-9d5be62e285c)

No "lock" button is displayed.

**Comment by ildar170975** [comment]
Seems to be working for rows only:
![image](https://github.com/iantrich/restriction-card/assets/71872483/891283d0-e33d-437b-afab-27bbf3e706f7)

**Comment by criticallimit** [comment]
Same here. After update restrictiuons are no longer working. The Lock is shown, but restrictions are ignored.

```yaml
type: entities
entities:
  - entity: switch.ladestation_switch
    name: Ladestation
    icon: mdi:usb
  - entity: switch.fernseher
    icon: hass:television
  - card:
      entity: switch.3d_drucker_switch
      name: 3D-Drucker
      icon: mdi:printer-3d-nozzle
      duration: 10
      state_color: true
    restrictions:
      confirm:
        text: ' Sicher?'
    type: custom:restriction-card
    row: true
    duration: 10
state_color: true
show_header_toggle: false
title: Wohnen
```
