### ISSUE TITLE
Entities card: no restiction on button 1.2.8 and 1.2.9 (1.2.7 works fine)

### ISSUE THREAD

**Issue by vingerha** [iantrich/restriction-card#95]
HA docker 2023.7.0
installed version of restriction card: 1.2.7 and 1.2.8
Issue: can toggle the switch
Workaround awaiting solution: downgrade to 1.2.7
![image](https://github.com/iantrich/restriction-card/assets/44190435/d62f2af4-5c8d-4981-8f05-c765de8a7ec1)

**Comment by ildar170975** [comment]
1.2.9
2023.7
Cannot reproduce:
![image](https://github.com/iantrich/restriction-card/assets/71872483/7ca45dee-12a6-47f2-8f2e-7ebd7366f043)
```
type: entities
title: xxx
entities:
  - type: custom:restriction-card
    row: true
    card:
      entity: switch.test_switch
    restrictions:
      pin:
        code: 1234
        text: xxxxx
```
