### ISSUE TITLE
Dynamic restrictions

### ISSUE THREAD

**Issue by pmkruyen** [iantrich/restriction-card#97]
👋

I want to lock/unlock a slider depending on the value of a boolean input (switch). 

‘Unfortunately, the code below does not work. Is it because the switch is not in a restriction card or is my code incorrect?

Thanks for your help. 

  ```
- title: Test
    path: Test
    badges: []
    cards:
      - type: entities
        entities:
          - input_boolean.ceiling_fan_state
      - type: entities
        entities:
          - card:
              entity: input_number.ceiling_fan_slider
              name: Slider
              secondary_info: last-changed
            restrictions:
              block: true
              condition:
                value: 'on'
                entity: input_boolean.ceiling_fan_state
                operator: '=='
            type: custom:restriction-card
            row: true
```

**Comment by pmkruyen** [comment]
I checked, but putting the switch in a restriction card has no effect.

**Comment by ildar170975** [comment]
Because this is wrong:
```
          restrictions:
            block: true
            condition:
              value: 'on'
              entity: input_boolean.ceiling_fan_state
              operator: '=='
```
https://github.com/iantrich/restriction-card#block-options
