### ISSUE TITLE
No longer working on Homeassistant 2023.7.3 on iOS

### ISSUE THREAD

**Issue by dgrnbrg** [iantrich/restriction-card#98]
**Checklist:**

- [x] I updated to the latest version available

**Release with the issue:**
2023.7.3

**Last working release (if known):**
2023.5.x

**Browser and Operating System:**
home assistant iOS app

**Description of problem:**

The restrictions work fine in Safari and Chrome on my laptop, and the restrictions even work in safari on iOS. They only fail to work (the lock isn't shown & I can immediately click) in the home assistant app.

**Comment by ildar170975** [comment]
No code = no issue.

**Comment by dgrnbrg** [comment]
```

type: custom:mod-card
style: |
  restriction-card {
    --restriction-lock-icon-size: 18px;
    --restriction-lock-margin-left: 95%;
  }
card:
  type: custom:restriction-card
  action: tap
  unlocked_icon: mdi:lock-off-outline
  duration: 2
  card:
    type: custom:mushroom-cover-card
    entity: cover.garage_door
    show_buttons_control: false
```

Looks like

![image](https://github.com/iantrich/restriction-card/assets/618507/e8f77171-a623-401a-a238-4982806f313d)

But it should have the restriction visible. On the safari browser, for instance, it looks like:

![image](https://github.com/iantrich/restriction-card/assets/618507/2b969807-d51a-47a3-ac38-81e13ce9ec27)

**Comment by ildar170975** [comment]
1. Test with a STANDARD card first, not with a custom mushroom one, and w/o any other custom plugins like card-mod.
2. This code works fine in iOS 15.x:
```
type: custom:mod-card
style: |
  restriction-card {
    --restriction-lock-icon-size: 12px;
    --restriction-lock-margin-left: 95%;
  }
card:
  type: custom:restriction-card
  action: tap
  unlocked_icon: mdi:lock-off-outline
  duration: 2
  card:
    type: entities
    entities:
      - entity: switch.test_switch
```

**Comment by dgrnbrg** [comment]
I've tested with a STANDARD card.

This code does not work on the HomeAssistant app with HA 2023.7.3 and iOS 16.1.1:

```
type: custom:restriction-card
action: tap
unlocked_icon: mdi:lock-off-outline
duration: 2
card:
  type: entity
  entity: cover.garage_door
  show_buttons_control: false
```

**Comment by ildar170975** [comment]
1. (unrelated) The `show_buttons_control` option does not exist for `entity` card.
2. Your code works in iOS 15.x (2023.8.0):
![image](https://github.com/iantrich/restriction-card/assets/71872483/7f5f53a7-ca91-4ef4-ae4e-ed6ebc382420)
```
type: custom:restriction-card
action: tap
unlocked_icon: mdi:lock-off-outline
duration: 2
card:
  type: entity
  entity: cover.test_garage_door
```
Check if your iOS device has a custom theme. Also, reset frontend cache.
