### ISSUE TITLE
code in secret

### ISSUE THREAD

**Issue by tux789-coder** [iantrich/restriction-card#99]
beautiful card I appreciate your work
I would like to define code inside secret.yaml on card I set code on !secret but card goes wrong any solution?

**Comment by ildar170975** [comment]
```
      type: custom:restriction-card
      restrictions:
        pin:
          code: !secret secret_pin
```
and secrets are supported in yaml mode of dashboards only.
Please close the issue if solved.
